name = "ODE"
uuid = "c030b06c-0b6d-57c2-b091-7029874bd033"
authors = ["Chris Rackauckas"]
version = "2.9.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Compat = "2.2, 3.0"
DiffEqBase = "6.5"
Polynomials = "0.6, 0.7, 0.8, 1.2"
Reexport = "0.2, 1"
julia = "1.3"

[extras]
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DiffEqProblemLibrary", "Test"]
